# Generated by Django 5.2.3 on 2025-08-28 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("business", "Business Person"), ("influencer", "Influencer")],
                default="influencer",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="session_token",
            field=models.CharField(default="0", max_length=10),
        ),
        migrations.CreateModel(
            name="Collaboration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        limit_choices_to={"role": "business"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_collabs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "influencer",
                    models.ForeignKey(
                        limit_choices_to={"role": "influencer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="influencer_collabs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
