# Generated by Django 5.2.3 on 2025-08-28 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_customuser_role_alter_customuser_session_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=150)),
                ("industry", models.CharField(max_length=100)),
                ("target_platform", models.CharField(max_length=100)),
                ("budget", models.PositiveIntegerField(default=0)),
                ("target_age", models.CharField(max_length=50)),
                ("target_location", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InfluencerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("niche", models.CharField(max_length=100)),
                ("platform", models.CharField(max_length=100)),
                ("followers", models.PositiveIntegerField(default=0)),
                ("engagement_rate", models.FloatField(default=0.0)),
                ("audience_age", models.CharField(max_length=50)),
                ("audience_location", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="influencer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Collaboration",
        ),
    ]
