# Generated by Django 5.2.3 on 2025-08-28 16:09

import api.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_businessprofile_influencerprofile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessprofile",
            name="target_platform",
        ),
        migrations.RemoveField(
            model_name="influencerprofile",
            name="platform",
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="target_platforms",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="influencerprofile",
            name="negative_reviews",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="influencerprofile",
            name="platforms",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="influencerprofile",
            name="positive_reviews",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="target_age",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="target_location",
            field=models.CharField(default="Global", max_length=100),
        ),
        migrations.AlterField(
            model_name="influencerprofile",
            name="audience_age",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="influencerprofile",
            name="audience_location",
            field=models.CharField(default="Global", max_length=100),
        ),
        migrations.AlterField(
            model_name="influencerprofile",
            name="engagement_rate",
            field=models.FloatField(default=api.user.models.random_engagement_rate),
        ),
        migrations.AlterField(
            model_name="influencerprofile",
            name="followers",
            field=models.PositiveIntegerField(default=api.user.models.random_followers),
        ),
    ]
