# Generated by Django 5.2.3 on 2025-08-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_businessprofile_target_platform_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="BusinessProfile/"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="user/"),
        ),
        migrations.AddField(
            model_name="influencerprofile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="Influencer/"),
        ),
    ]
